// upload/uploadConstants.js

export const SHIP_TYPES = [
    { value: 'AEW Aircraft', label: 'AEW Aircraft' },
    { value: 'Air Cushion Vehicle', label: 'Air Cushion Vehicle' },
    { value: 'Aircraft Carrier', label: 'Aircraft Carrier' },
    { value: 'Ambulance Boat', label: 'Ambulance Boat' },
    { value: 'Amphibious Assault Ship', label: 'Amphibious Assault Ship' },
    { value: 'Amphibious Transport Dock', label: 'Amphibious Transport Dock' },
    { value: 'Antarctic Survey Ship (AGOBH)', label: 'Antarctic Survey Ship (AGOBH)' },
    { value: 'Auxiliary', label: 'Auxiliary' },
    { value: 'Auxiliary Landing Ship Dock', label: 'Auxiliary Landing Ship Dock' },
    { value: 'Auxiliary Ocean Tug', label: 'Auxiliary Ocean Tug' },
    { value: 'Auxiliary Repair Dock', label: 'Auxiliary Repair Dock' },
    { value: 'Auxiliary Training Minehunter', label: 'Auxiliary Training Minehunter' },
    { value: 'Ballistic Missile Submarine', label: 'Ballistic Missile Submarine' },
    { value: 'Buoy Tender', label: 'Buoy Tender' },
    { value: 'Cable Ship', label: 'Cable Ship' },
    { value: 'Cargo Ship', label: 'Cargo Ship' },
    { value: 'Cargo Ship Helicopter', label: 'Cargo Ship Helicopter' },
    { value: 'Catamaran', label: 'Catamaran' },
    { value: 'Coast Guard', label: 'Coast Guard' },
    { value: 'Coastal Minehunter', label: 'Coastal Minehunter' },
    { value: 'Coastal Minehunter / Coastal Minesweeper', label: 'Coastal Minehunter / Coastal Minesweeper' },
    { value: 'Coastal Minesweeper', label: 'Coastal Minesweeper' },
    { value: 'Coastal Minesweeper / Oceanographic Research Ship', label: 'Coastal Minesweeper / Oceanographic Research Ship' },
    { value: 'Coastal Patrol Boat', label: 'Coastal Patrol Boat' },
    { value: 'Coastal Patrol Craft', label: 'Coastal Patrol Craft' },
    { value: 'Coastal Patrol Ship', label: 'Coastal Patrol Ship' },
    { value: 'Coastal Patrol Vessel', label: 'Coastal Patrol Vessel' },
    { value: 'Coastal Survey Ship', label: 'Coastal Survey Ship' },
    { value: 'Coastal Transport', label: 'Coastal Transport' },
    { value: 'Coastal Tug (YTB)', label: 'Coastal Tug (YTB)' },
    { value: 'Command Craft', label: 'Command Craft' },
    { value: 'Command Launch', label: 'Command Launch' },
    { value: 'Command Ship', label: 'Command Ship' },
    { value: 'Command Ship / Repair Ship', label: 'Command Ship / Repair Ship' },
    { value: 'Command Ship/Launch Barge', label: 'Command Ship/Launch Barge' },
    { value: 'Command/Support Ship', label: 'Command/Support Ship' },
    { value: 'Construction Tender', label: 'Construction Tender' },
    { value: 'Corvette', label: 'Corvette' },
    { value: 'Corvette/Training Ship', label: 'Corvette/Training Ship' },
    { value: 'Cruiser', label: 'Cruiser' },
    { value: 'Cutter', label: 'Cutter' },
    { value: 'Deep Submergence Rescue Vehicle', label: 'Deep Submergence Rescue Vehicle' },
    { value: 'Deep Submergence Vehicle', label: 'Deep Submergence Vehicle' },
    { value: 'Degaussing Ship', label: 'Degaussing Ship' },
    { value: 'Degaussing Vessel', label: 'Degaussing Vessel' },
    { value: 'Destroyer', label: 'Destroyer' },
    { value: 'Destroyer / LCC', label: 'Destroyer / LCC' },
    { value: 'Diving Tender', label: 'Diving Tender' },
    { value: 'Diving Tender/Command Ship', label: 'Diving Tender/Command Ship' },
    { value: 'Dock Landing Ship', label: 'Dock Landing Ship' },
    { value: 'Experimental Ship', label: 'Experimental Ship' },
    { value: 'Fast Attack Craft', label: 'Fast Attack Craft' },
    { value: 'Fast Coastal Patrol Boat', label: 'Fast Coastal Patrol Boat' },
    { value: 'Fast Combat Support Ship', label: 'Fast Combat Support Ship' },
    { value: 'Fast Guided Missile Patrol Craft', label: 'Fast Guided Missile Patrol Craft' },
    { value: 'Fast Guided Missile Torpedo Boat', label: 'Fast Guided Missile Torpedo Boat' },
    { value: 'Fast Intercept Craft', label: 'Fast Intercept Craft' },
    { value: 'Fast Landing Craft Personnel', label: 'Fast Landing Craft Personnel' },
    { value: 'Fast Patrol Boat', label: 'Fast Patrol Boat' },
    { value: 'Fast Patrol Craft', label: 'Fast Patrol Craft' },
    { value: 'Fast Response Cutter', label: 'Fast Response Cutter' },
    { value: 'Ferry Boat', label: 'Ferry Boat' },
    { value: 'Ferry Boat/Degaussing Vessel', label: 'Ferry Boat/Degaussing Vessel' },
    { value: 'Firefighting Vessel', label: 'Firefighting Vessel' },
    { value: 'Floating Dry Dock', label: 'Floating Dry Dock' },
    { value: 'Fleet Logistic Tanker (AORH)', label: 'Fleet Logistic Tanker (AORH)' },
    { value: 'Fleet Ocean Tug', label: 'Fleet Ocean Tug' },
    { value: 'Fleet Ocean Tug/Salvage Ship', label: 'Fleet Ocean Tug/Salvage Ship' },
    { value: 'Fleet Replenishment Ship (AORH)', label: 'Fleet Replenishment Ship (AORH)' },
    { value: 'Freighter', label: 'Freighter' },
    { value: 'Frigate', label: 'Frigate' },
    { value: 'Frigate/Corvette (FFG/FFGH)', label: 'Frigate/Corvette (FFG/FFGH)' },
    { value: 'Fuel Oil Barge', label: 'Fuel Oil Barge' },
    { value: 'Gunship', label: 'Gunship' },
    { value: 'Guided Missile Aircraft Carrier', label: 'Guided Missile Aircraft Carrier' },
    { value: 'Guided Missile Destroyer', label: 'Guided Missile Destroyer' },
    { value: 'Guided Missile Frigate', label: 'Guided Missile Frigate' },
    { value: 'Guided Missile Helicopter Cruiser', label: 'Guided Missile Helicopter Cruiser' },
    { value: 'Guided Missile Helicopter Destroyer', label: 'Guided Missile Helicopter Destroyer' },
    { value: 'Guided Missile Helicopter Frigate', label: 'Guided Missile Helicopter Frigate' },
    { value: 'Guided Missile Helicopter Patrol Craft', label: 'Guided Missile Helicopter Patrol Craft' },
    { value: 'Guided Missile Motor Torpedo Boat', label: 'Guided Missile Motor Torpedo Boat' },
    { value: 'Guided Missile Nuclear Submarine', label: 'Guided Missile Nuclear Submarine' },
    { value: 'Guided Missile Patrol Craft', label: 'Guided Missile Patrol Craft' },
    { value: 'Guided Missile Submarine', label: 'Guided Missile Submarine' },
    { value: 'Harbour Craft', label: 'Harbour Craft' },
    { value: 'Harbour Patrol Craft', label: 'Harbour Patrol Craft' },
    { value: 'Harbour Tanker', label: 'Harbour Tanker' },
    { value: 'Harbour Tug', label: 'Harbour Tug' },
    { value: 'Harbour Tugs (YAG/YTB)', label: 'Harbour Tugs (YAG/YTB)' },
    { value: 'Headquarters Ship', label: 'Headquarters Ship' },
    { value: 'Helicopter', label: 'Helicopter' },
    { value: 'Helicopter Carrier', label: 'Helicopter Carrier' },
    { value: 'Helicopter Command Ship', label: 'Helicopter Command Ship' },
    { value: 'Helicopter Cruiser', label: 'Helicopter Cruiser' },
    { value: 'Helicopter Destroyer', label: 'Helicopter Destroyer' },
    { value: 'Helicopter Frigate', label: 'Helicopter Frigate' },
    { value: 'Helicopter Landing Ship Logistic', label: 'Helicopter Landing Ship Logistic' },
    { value: 'Helicopter Landing Ship Tank', label: 'Helicopter Landing Ship Tank' },
    { value: 'Helicopter Landing Ship Tank / Minelayer', label: 'Helicopter Landing Ship Tank / Minelayer' },
    { value: 'Helicopter Offshore Patrol Boat', label: 'Helicopter Offshore Patrol Boat' },
    { value: 'Helicopter Repair Dock', label: 'Helicopter Repair Dock' },
    { value: 'Helicopter Repair Ship', label: 'Helicopter Repair Ship' },
    { value: 'Helicopter Replenishment Oiler', label: 'Helicopter Replenishment Oiler' },
    { value: 'High Speed Vessel', label: 'High Speed Vessel' },
    { value: 'Hospital Ship', label: 'Hospital Ship' },
    { value: 'Hovercraft', label: 'Hovercraft' },
    { value: 'Hunter-Killer Submarine', label: 'Hunter-Killer Submarine' },
    { value: 'Hydrofoil', label: 'Hydrofoil' },
    { value: 'Hydrographic Survey Boat', label: 'Hydrographic Survey Boat' },
    { value: 'Hydrographic Survey Ship', label: 'Hydrographic Survey Ship' },
    { value: 'Icebreaker', label: 'Icebreaker' },
    { value: 'Icebreaker / Support', label: 'Icebreaker / Support' },
    { value: 'Icebreaker, Buoy Tender', label: 'Icebreaker, Buoy Tender' },
    { value: 'Inshore Minesweeper', label: 'Inshore Minesweeper' },
    { value: 'Inshore Minesweeper / Patrol Craft', label: 'Inshore Minesweeper / Patrol Craft' },
    { value: 'Inshore Patrol Boat', label: 'Inshore Patrol Boat' },
    { value: 'Inshore Patrol Craft', label: 'Inshore Patrol Craft' },
    { value: 'Inshore Patrol Craft (PB)', label: 'Inshore Patrol Craft (PB)' },
    { value: 'Inshore Survey Craft', label: 'Inshore Survey Craft' },
    { value: 'Inshore/River Patrol Launch (PBR)', label: 'Inshore/River Patrol Launch (PBR)' },
    { value: 'Intelligence Collector', label: 'Intelligence Collector' },
    { value: 'Interception Craft', label: 'Interception Craft' },
    { value: 'Interceptor', label: 'Interceptor' },
    { value: 'Lake Hospital Craft', label: 'Lake Hospital Craft' },
    { value: 'Landing Craft', label: 'Landing Craft' },
    { value: 'Landing Craft (LCT)', label: 'Landing Craft (LCT)' },
    { value: 'Landing Craft (LCU)', label: 'Landing Craft (LCU)' },
    { value: 'Landing Craft Air Cushion', label: 'Landing Craft Air Cushion' },
    { value: 'Landing Craft Mechanized', label: 'Landing Craft Mechanized' },
    { value: 'Landing Craft Mechanized (LCM)', label: 'Landing Craft Mechanized (LCM)' },
    { value: 'Landing Craft Mechanized/Vehicle Personnel/Landing Craft Personnel', label: 'Landing Craft Mechanized/Vehicle Personnel/Landing Craft Personnel' },
    { value: 'Landing Craft Personnel', label: 'Landing Craft Personnel' },
    { value: 'Landing Craft Tank', label: 'Landing Craft Tank' },
    { value: 'Landing Craft Tank (LCT)', label: 'Landing Craft Tank (LCT)' },
    { value: 'Landing Craft Utility', label: 'Landing Craft Utility' },
    { value: 'Landing Craft Utility (LCU)', label: 'Landing Craft Utility (LCU)' },
    { value: 'Landing Craft Vehicle Personnel', label: 'Landing Craft Vehicle Personnel' },
    { value: 'Landing Craft/Landing Platform', label: 'Landing Craft/Landing Platform' },
    { value: 'Landing Helicopter Dock (LHD)', label: 'Landing Helicopter Dock (LHD)' },
    { value: 'Landing Platform Dock', label: 'Landing Platform Dock' },
    { value: 'Landing Platform Dock (LPD)', label: 'Landing Platform Dock (LPD)' },
    { value: 'Landing Ship', label: 'Landing Ship' },
    { value: 'Landing Ship (Logistic)', label: 'Landing Ship (Logistic)' },
    { value: 'Landing Ship (LSTH)', label: 'Landing Ship (LSTH)' },
    { value: 'Landing Ship Dock', label: 'Landing Ship Dock' },
    { value: 'Landing Ship Dock (LSDH)', label: 'Landing Ship Dock (LSDH)' },
    { value: 'Landing Ship Logistic', label: 'Landing Ship Logistic' },
    { value: 'Landing Ship Medium', label: 'Landing Ship Medium' },
    { value: 'Landing Ship Medium (LSM)', label: 'Landing Ship Medium (LSM)' },
    { value: 'Landing Ship Tank', label: 'Landing Ship Tank' },
    { value: 'Large Harbor Tug', label: 'Large Harbor Tug' },
    { value: 'Large Infantry Landing Ship', label: 'Large Infantry Landing Ship' },
    { value: 'Large Patrol Craft', label: 'Large Patrol Craft' },
    { value: 'Large Patrol Craft (PB)', label: 'Large Patrol Craft (PB)' },
    { value: 'Large Patrol Craft (PC)', label: 'Large Patrol Craft (PC)' },
    { value: 'Large Patrol Craft (PG)', label: 'Large Patrol Craft (PG)' },
    { value: 'Large Patrol Vessel', label: 'Large Patrol Vessel' },
    { value: 'Large/Medium/Small Harbor Tug', label: 'Large/Medium/Small Harbor Tug' },
    { value: 'LCU Transport', label: 'LCU Transport' },
    { value: 'Light Cargo', label: 'Light Cargo' },
    { value: 'Light Cargo Ship', label: 'Light Cargo Ship' },
    { value: 'Light Frigate', label: 'Light Frigate' },
    { value: 'Light Guided Missile Frigate', label: 'Light Guided Missile Frigate' },
    { value: 'Light Replenishment Oiler', label: 'Light Replenishment Oiler' },
    { value: 'LST/Minelayer', label: 'LST/Minelayer' },
    { value: 'Maritime Patrol Aircraft', label: 'Maritime Patrol Aircraft' },
    { value: 'Medium Endurance Cutter', label: 'Medium Endurance Cutter' },
    { value: 'Medium Harbor Tug', label: 'Medium Harbor Tug' },
    { value: 'Medium Landing Ship', label: 'Medium Landing Ship' },
    { value: 'Medium Landing Ship Tank', label: 'Medium Landing Ship Tank' },
    { value: 'Midget Submarine', label: 'Midget Submarine' },
    { value: 'Mine Countermeasures', label: 'Mine Countermeasures' },
    { value: 'Mine Countermeasures Command Ship', label: 'Mine Countermeasures Command Ship' },
    { value: 'Mine Countermeasures Ship', label: 'Mine Countermeasures Ship' },
    { value: 'Minehunter', label: 'Minehunter' },
    { value: 'Minehunter / Coastal Drone Minesweeper', label: 'Minehunter / Coastal Drone Minesweeper' },
    { value: 'Minehunter / Diving Tender', label: 'Minehunter / Diving Tender' },
    { value: 'Minehunter Coastal (MHC)', label: 'Minehunter Coastal (MHC)' },
    { value: 'Minehunter/Coastal', label: 'Minehunter/Coastal' },
    { value: 'Minehunter/Minesweeper', label: 'Minehunter/Minesweeper' },
    { value: 'Minehunter/Sweeper', label: 'Minehunter/Sweeper' },
    { value: 'Minehunter—Coastal (MHC)', label: 'Minehunter—Coastal (MHC)' },
    { value: 'Minelayer / Minesweeper Tender', label: 'Minelayer / Minesweeper Tender' },
    { value: 'Minelayer/Mine Countermeasures Ship', label: 'Minelayer/Mine Countermeasures Ship' },
    { value: 'Minesweeper', label: 'Minesweeper' },
    { value: 'Minesweeper - Ocean', label: 'Minesweeper - Ocean' },
    { value: 'Minesweeper Drone', label: 'Minesweeper Drone' },
    { value: 'Minesweeper/Hunter', label: 'Minesweeper/Hunter' },
    { value: 'Minesweeper—Inshore', label: 'Minesweeper—Inshore' },
    { value: 'Miscellaneous Auxiliary', label: 'Miscellaneous Auxiliary' },
    { value: 'Miscellaneous Auxiliary/Diving Tender', label: 'Miscellaneous Auxiliary/Diving Tender' },
    { value: 'Miscellaneous Command Ship', label: 'Miscellaneous Command Ship' },
    { value: 'Missile Cargo Ship', label: 'Missile Cargo Ship' },
    { value: 'Missile Range Instrumentation Ship', label: 'Missile Range Instrumentation Ship' },
    { value: 'Motor Torpedo Boat Tender', label: 'Motor Torpedo Boat Tender' },
    { value: 'Motor Torpedo Boat Tender / Submarine Tender', label: 'Motor Torpedo Boat Tender / Submarine Tender' },
    { value: 'Nuclear Submarine (SSN)', label: 'Nuclear Submarine (SSN)' },
    { value: 'Nuclear-Powered Guided Missile Helicopter Cruiser', label: 'Nuclear-Powered Guided Missile Helicopter Cruiser' },
    { value: 'Nuclear-Powered Submarine', label: 'Nuclear-Powered Submarine' },
    { value: 'Nuclear-Powered Submarine/Guided Missile Nuclear Submarine', label: 'Nuclear-Powered Submarine/Guided Missile Nuclear Submarine' },
    { value: 'Ocean Minesweeper', label: 'Ocean Minesweeper' },
    { value: 'Ocean Surveillance', label: 'Ocean Surveillance' },
    { value: 'Ocean Tug', label: 'Ocean Tug' },
    { value: 'Oceanographic Research Ship', label: 'Oceanographic Research Ship' },
    { value: 'Offshore Patrol (PSOH)', label: 'Offshore Patrol (PSOH)' },
    { value: 'Offshore Patrol Boat', label: 'Offshore Patrol Boat' },
    { value: 'Offshore Patrol Craft (PSO)', label: 'Offshore Patrol Craft (PSO)' },
    { value: 'Offshore Patrol Craft (PSOH)', label: 'Offshore Patrol Craft (PSOH)' },
    { value: 'Offshore Patrol Ship', label: 'Offshore Patrol Ship' },
    { value: 'Offshore Patrol Ship / Helicopter Offshore Patrol Ship', label: 'Offshore Patrol Ship / Helicopter Offshore Patrol Ship' },
    { value: 'Offshore Patrol Vessel', label: 'Offshore Patrol Vessel' },
    { value: 'Offshore Patrol Vessel (PSOH)', label: 'Offshore Patrol Vessel (PSOH)' },
    { value: 'Oiler', label: 'Oiler' },
    { value: 'Oiler / Transport Oiler', label: 'Oiler / Transport Oiler' },
    { value: 'Patrol Boat', label: 'Patrol Boat' },
    { value: 'Patrol Boat / Medium Landing Ship', label: 'Patrol Boat / Medium Landing Ship' },
    { value: 'Patrol Boat/Training (PB/AXL)', label: 'Patrol Boat/Training (PB/AXL)' },
    { value: 'Patrol Boat/Training Ship', label: 'Patrol Boat/Training Ship' },
    { value: 'Patrol Coastal Ship', label: 'Patrol Coastal Ship' },
    { value: 'Patrol Craft', label: 'Patrol Craft' },
    { value: 'Patrol Gunboat', label: 'Patrol Gunboat' },
    { value: 'Patrol Ship', label: 'Patrol Ship' },
    { value: 'Patrol Ship (PG)', label: 'Patrol Ship (PG)' },
    { value: 'Patrol Ship (PSO)', label: 'Patrol Ship (PSO)' },
    { value: 'Patrol Vessel', label: 'Patrol Vessel' },
    { value: 'Pollution Control Vessel', label: 'Pollution Control Vessel' },
    { value: 'Raiding Craft', label: 'Raiding Craft' },
    { value: 'Repair Cargo Ship / Survey Ship', label: 'Repair Cargo Ship / Survey Ship' },
    { value: 'Repair Ship', label: 'Repair Ship' },
    { value: 'Replenishment Oiler', label: 'Replenishment Oiler' },
    { value: 'Replenishment Oiler Helicopter', label: 'Replenishment Oiler Helicopter' },
    { value: 'Replenishment Oiler Helicopter / Hydrographic Survey Ship', label: 'Replenishment Oiler Helicopter / Hydrographic Survey Ship' },
    { value: 'Replenishment Ship', label: 'Replenishment Ship' },
    { value: 'Replenishment Tanker', label: 'Replenishment Tanker' },
    { value: 'Replenishment Tanker (AORH)', label: 'Replenishment Tanker (AORH)' },
    { value: 'Research Oceanographic Ship', label: 'Research Oceanographic Ship' },
    { value: 'Research Ship', label: 'Research Ship' },
    { value: 'Research Vessel', label: 'Research Vessel' },
    { value: 'Rescue Tug', label: 'Rescue Tug' },
    { value: 'Response Boat', label: 'Response Boat' },
    { value: 'River Assault Craft', label: 'River Assault Craft' },
    { value: 'River Gunboat', label: 'River Gunboat' },
    { value: 'River Hospital Craft', label: 'River Hospital Craft' },
    { value: 'River Minesweeper', label: 'River Minesweeper' },
    { value: 'River Patrol Boat', label: 'River Patrol Boat' },
    { value: 'River Patrol Craft', label: 'River Patrol Craft' },
    { value: 'River Survey Craft', label: 'River Survey Craft' },
    { value: 'River Tender', label: 'River Tender' },
    { value: 'Sail Training Craft', label: 'Sail Training Craft' },
    { value: 'Sail Training Ship', label: 'Sail Training Ship' },
    { value: 'Sail Training Ship (AXS)', label: 'Sail Training Ship (AXS)' },
    { value: 'Salvage and Rescue Tug', label: 'Salvage and Rescue Tug' },
    { value: 'Salvage Ship', label: 'Salvage Ship' },
    { value: 'Salvage Tug', label: 'Salvage Tug' },
    { value: 'SAR Craft', label: 'SAR Craft' },
    { value: 'Search and Rescue Craft', label: 'Search and Rescue Craft' },
    { value: 'Small Harbor Tug', label: 'Small Harbor Tug' },
    { value: 'Special Operations Craft', label: 'Special Operations Craft' },
    { value: 'Store Issue Ship', label: 'Store Issue Ship' },
    { value: 'Store Issue Ship / Training Ship', label: 'Store Issue Ship / Training Ship' },
    { value: 'Store Issue Ship/Water Tanker', label: 'Store Issue Ship/Water Tanker' },
    { value: 'Submarine', label: 'Submarine' },
    { value: 'Submarine Rescue Ship', label: 'Submarine Rescue Ship' },
    { value: 'Submarine Tender', label: 'Submarine Tender' },
    { value: 'Submarine Tender / Torpedo Trials Craft', label: 'Submarine Tender / Torpedo Trials Craft' },
    { value: 'Support Craft', label: 'Support Craft' },
    { value: 'Support Ship', label: 'Support Ship' },
    { value: 'Survey and Research Ship', label: 'Survey and Research Ship' },
    { value: 'Survey Craft', label: 'Survey Craft' },
    { value: 'Survey Ship', label: 'Survey Ship' },
    { value: 'Survey Ship / Oiler', label: 'Survey Ship / Oiler' },
    { value: 'Survey Ship / Vehicle Cargo Ship', label: 'Survey Ship / Vehicle Cargo Ship' },
    { value: 'Survey/Patrol', label: 'Survey/Patrol' },
    { value: 'Tank Landing Ship', label: 'Tank Landing Ship' },
    { value: 'Tanker', label: 'Tanker' },
    { value: 'Torpedo Recovery Craft', label: 'Torpedo Recovery Craft' },
    { value: 'Torpedo Recovery Vessel', label: 'Torpedo Recovery Vessel' },
    { value: 'Training Craft', label: 'Training Craft' },
    { value: 'Training Frigate', label: 'Training Frigate' },
    { value: 'Training Ship', label: 'Training Ship' },
    { value: 'Trials Ship', label: 'Trials Ship' },
    { value: 'Transport', label: 'Transport' },
    { value: 'Transport / LCU', label: 'Transport / LCU' },
    { value: 'Transport Oiler', label: 'Transport Oiler' },
    { value: 'Transport Ship', label: 'Transport Ship' },
    { value: 'Tug', label: 'Tug' },
    { value: 'Unmanned Surface Vehicle', label: 'Unmanned Surface Vehicle' },
    { value: 'Utility Air Cushion Vehicle', label: 'Utility Air Cushion Vehicle' },
    { value: 'Utility Craft', label: 'Utility Craft' },
    { value: 'Vehicle Cargo Ship', label: 'Vehicle Cargo Ship' },
    { value: 'Water Barge', label: 'Water Barge' },
    { value: 'Water Tanker', label: 'Water Tanker' },
    { value: 'Yacht', label: 'Yacht' }
];

export const SHIP_ROLES = [
    { value: 'AAW', label: 'AAW' },
    { value: 'Air Defense', label: 'Air Defense' },
    { value: 'Air Defence Destroyer', label: 'Air Defence Destroyer' },
    { value: 'Air Defence Frigate', label: 'Air Defence Frigate' },
    { value: 'Air Warfare', label: 'Air Warfare' },
    { value: 'Airborne Early Warning', label: 'Airborne Early Warning' },
    { value: 'Aids to Navigation', label: 'Aids to Navigation' },
    { value: 'Amphibious', label: 'Amphibious' },
    { value: 'Amphibious Assault', label: 'Amphibious Assault' },
    { value: 'Amphibious Assault, Training', label: 'Amphibious Assault, Training' },
    { value: 'Amphibious Landing', label: 'Amphibious Landing' },
    { value: 'Amphibious Transport', label: 'Amphibious Transport' },
    { value: 'Amphibious Transport Dock', label: 'Amphibious Transport Dock' },
    { value: 'Amphibious Transport, Minelayer', label: 'Amphibious Transport, Minelayer' },
    { value: 'Amphibious Warfare', label: 'Amphibious Warfare' },
    { value: 'Amphibious assault, aviation platform', label: 'Amphibious assault, aviation platform' },
    { value: 'Amphibious assault, strategic projection', label: 'Amphibious assault, strategic projection' },
    { value: 'Amphibious transport, landing craft platform', label: 'Amphibious transport, landing craft platform' },
    { value: 'Amphibious/SAR', label: 'Amphibious/SAR' },
    { value: 'Antarctic Support', label: 'Antarctic Support' },
    { value: 'Anti-Air', label: 'Anti-Air' },
    { value: 'Anti-Ship', label: 'Anti-Ship' },
    { value: 'Anti-Ship / ASW', label: 'Anti-Ship / ASW' },
    { value: 'Anti-Submarine', label: 'Anti-Submarine' },
    { value: 'Anti-Submarine Warfare / Anti-Surface Vessel', label: 'Anti-Submarine Warfare / Anti-Surface Vessel' },
    { value: 'Anti-Submarine Warfare Carrier', label: 'Anti-Submarine Warfare Carrier' },
    { value: 'Anti-Submarine, Anti-Air', label: 'Anti-Submarine, Anti-Air' },
    { value: 'Anti-Surface', label: 'Anti-Surface' },
    { value: 'Anti-Surface Warfare', label: 'Anti-Surface Warfare' },
    { value: 'Anti-Surface, Anti-Air', label: 'Anti-Surface, Anti-Air' },
    { value: 'Anti-Surface, patrol', label: 'Anti-Surface, patrol' },
    { value: 'Anti-air, anti-submarine, anti-surface', label: 'Anti-air, anti-submarine, anti-surface' },
    { value: 'Assault', label: 'Assault' },
    { value: 'Assault Ship', label: 'Assault Ship' },
    { value: 'Assault, Patrol', label: 'Assault, Patrol' },
    { value: 'Attack', label: 'Attack' },
    { value: 'Attack Transport', label: 'Attack Transport' },
    { value: 'Attack submarine', label: 'Attack submarine' },
    { value: 'Auxiliary', label: 'Auxiliary' },
    { value: 'Auxiliary / Minelayer', label: 'Auxiliary / Minelayer' },
    { value: 'Auxiliary, Repair', label: 'Auxiliary, Repair' },
    { value: 'Auxiliary/Tug', label: 'Auxiliary/Tug' },
    { value: 'Ballistic Missile Submarine', label: 'Ballistic Missile Submarine' },
    { value: 'Barracks Ship', label: 'Barracks Ship' },
    { value: 'Battle Cruiser', label: 'Battle Cruiser' },
    { value: 'Boom Defence', label: 'Boom Defence' },
    { value: 'Boom Defence/Salvage', label: 'Boom Defence/Salvage' },
    { value: 'Buoy Tender', label: 'Buoy Tender' },
    { value: 'Cable Layer', label: 'Cable Layer' },
    { value: 'Ceremonial', label: 'Ceremonial' },
    { value: 'Coast Guard', label: 'Coast Guard' },
    { value: 'Coastal ASW / Patrol', label: 'Coastal ASW / Patrol' },
    { value: 'Coastal Minehunter', label: 'Coastal Minehunter' },
    { value: 'Coastal Minesweeper', label: 'Coastal Minesweeper' },
    { value: 'Coastal Patrol', label: 'Coastal Patrol' },
    { value: 'Coastal Patrol Craft', label: 'Coastal Patrol Craft' },
    { value: 'Coastal Patrol Ship', label: 'Coastal Patrol Ship' },
    { value: 'Coastal Patrol Vessel', label: 'Coastal Patrol Vessel' },
    { value: 'Coastal Surveillance', label: 'Coastal Surveillance' },
    { value: 'Coastal Transport, Supply', label: 'Coastal Transport, Supply' },
    { value: 'Coastal Tug', label: 'Coastal Tug' },
    { value: 'Coastal patrol, law enforcement', label: 'Coastal patrol, law enforcement' },
    { value: 'Coastal/Infiltration', label: 'Coastal/Infiltration' },
    { value: 'Coastal/River Patrol', label: 'Coastal/River Patrol' },
    { value: 'Combat Support Ship', label: 'Combat Support Ship' },
    { value: 'Command', label: 'Command' },
    { value: 'Command & Control', label: 'Command & Control' },
    { value: 'Command / Transport', label: 'Command / Transport' },
    { value: 'Command Ship/Research', label: 'Command Ship/Research' },
    { value: 'Command, AAW', label: 'Command, AAW' },
    { value: 'Command/Support/Research', label: 'Command/Support/Research' },
    { value: 'Construction, AtoN', label: 'Construction, AtoN' },
    { value: 'Corvette', label: 'Corvette' },
    { value: 'Corvette, ASW', label: 'Corvette, ASW' },
    { value: 'Corvette, Missile', label: 'Corvette, Missile' },
    { value: 'Cruise Missile Submarine', label: 'Cruise Missile Submarine' },
    { value: 'Cruiser', label: 'Cruiser' },
    { value: 'Cutter', label: 'Cutter' },
    { value: 'Deep sea research', label: 'Deep sea research' },
    { value: 'Degaussing Vessel', label: 'Degaussing Vessel' },
    { value: 'Destroyer', label: 'Destroyer' },
    { value: 'Destroyer, Surface Warfare', label: 'Destroyer, Surface Warfare' },
    { value: 'Diver Delivery', label: 'Diver Delivery' },
    { value: 'Diver Support', label: 'Diver Support' },
    { value: 'Diving Support', label: 'Diving Support' },
    { value: 'Diving Tender', label: 'Diving Tender' },
    { value: 'Diving/Mine Clearance', label: 'Diving/Mine Clearance' },
    { value: 'Dock Landing Ship', label: 'Dock Landing Ship' },
    { value: 'Drug Interdiction', label: 'Drug Interdiction' },
    { value: 'Drug Interdiction, SAR', label: 'Drug Interdiction, SAR' },
    { value: 'EEZ Patrol, Surveillance', label: 'EEZ Patrol, Surveillance' },
    { value: 'Electronic Surveillance', label: 'Electronic Surveillance' },
    { value: 'Equipment Trials', label: 'Equipment Trials' },
    { value: 'Fast Attack Craft', label: 'Fast Attack Craft' },
    { value: 'Fast Attack Craft - Gun', label: 'Fast Attack Craft - Gun' },
    { value: 'Fast Attack Craft - Missile', label: 'Fast Attack Craft - Missile' },
    { value: 'Fast Attack Craft - Patrol', label: 'Fast Attack Craft - Patrol' },
    { value: 'Fast Attack Craft (Gun/Missile)', label: 'Fast Attack Craft (Gun/Missile)' },
    { value: 'Fast Attack Craft, Missile Hydrofoil', label: 'Fast Attack Craft, Missile Hydrofoil' },
    { value: 'Fast Attack Craft, Patrol Hydrofoil', label: 'Fast Attack Craft, Patrol Hydrofoil' },
    { value: 'Fast Attack Craft-Missile', label: 'Fast Attack Craft-Missile' },
    { value: 'Fast Attack Craft-Missile Hydrofoil', label: 'Fast Attack Craft-Missile Hydrofoil' },
    { value: 'Fast Attack Missile', label: 'Fast Attack Missile' },
    { value: 'Fast Attack-Missile', label: 'Fast Attack-Missile' },
    { value: 'Fast Combat Support Ship', label: 'Fast Combat Support Ship' },
    { value: 'Fast Missile Torpedo Boat', label: 'Fast Missile Torpedo Boat' },
    { value: 'Fast Patrol Boat', label: 'Fast Patrol Boat' },
    { value: 'Fast Patrol Craft', label: 'Fast Patrol Craft' },
    { value: 'Fast Supply/Transport', label: 'Fast Supply/Transport' },
    { value: 'Firefighting', label: 'Firefighting' },
    { value: 'Fisheries Protection', label: 'Fisheries Protection' },
    { value: 'Fishery Protection', label: 'Fishery Protection' },
    { value: 'Fishery protection, interdiction, search and rescue', label: 'Fishery protection, interdiction, search and rescue' },
    { value: 'Fishery/EEZ Patrol', label: 'Fishery/EEZ Patrol' },
    { value: 'Flagship/Command', label: 'Flagship/Command' },
    { value: 'Fleet Ocean Tug', label: 'Fleet Ocean Tug' },
    { value: 'Fleet Replenishment', label: 'Fleet Replenishment' },
    { value: 'Fleet Tanker', label: 'Fleet Tanker' },
    { value: 'Fleet Tug/Salvage', label: 'Fleet Tug/Salvage' },
    { value: 'Fleet command and control', label: 'Fleet command and control' },
    { value: 'Floating Dock', label: 'Floating Dock' },
    { value: 'Forward Repair Ship', label: 'Forward Repair Ship' },
    { value: 'Frigate', label: 'Frigate' },
    { value: 'Frigate (to be OPV)', label: 'Frigate (to be OPV)' },
    { value: 'Frigate, ASW', label: 'Frigate, ASW' },
    { value: 'Frigate/Corvette', label: 'Frigate/Corvette' },
    { value: 'Fuel Transport', label: 'Fuel Transport' },
    { value: 'General Purpose', label: 'General Purpose' },
    { value: 'General Transport', label: 'General Transport' },
    { value: 'Guided Missile Attack', label: 'Guided Missile Attack' },
    { value: 'Guided Missile Corvette', label: 'Guided Missile Corvette' },
    { value: 'Guided Missile Destroyer', label: 'Guided Missile Destroyer' },
    { value: 'Guided Missile Frigate', label: 'Guided Missile Frigate' },
    { value: 'Guided Missile Helicopter Destroyer', label: 'Guided Missile Helicopter Destroyer' },
    { value: 'Guided Missile Helicopter Frigate', label: 'Guided Missile Helicopter Frigate' },
    { value: 'Guided Missile Motor Torpedo Boat', label: 'Guided Missile Motor Torpedo Boat' },
    { value: 'Guided Missile Patrol Craft', label: 'Guided Missile Patrol Craft' },
    { value: 'Gun Boat', label: 'Gun Boat' },
    { value: 'Gunboat', label: 'Gunboat' },
    { value: 'Harbour Patrol', label: 'Harbour Patrol' },
    { value: 'Harbour Tanker', label: 'Harbour Tanker' },
    { value: 'Harbour Tug', label: 'Harbour Tug' },
    { value: 'Heavy Lift Ship', label: 'Heavy Lift Ship' },
    { value: 'Heavy icebreaking, polar operations', label: 'Heavy icebreaking, polar operations' },
    { value: 'Helicopter Carrier', label: 'Helicopter Carrier' },
    { value: 'Helicopter Frigate', label: 'Helicopter Frigate' },
    { value: 'High-speed amphibious landing', label: 'High-speed amphibious landing' },
    { value: 'High-speed insertion/extraction of SEAL teams', label: 'High-speed insertion/extraction of SEAL teams' },
    { value: 'Historical display, ceremonial', label: 'Historical display, ceremonial' },
    { value: 'Hospital', label: 'Hospital' },
    { value: 'Hovercraft', label: 'Hovercraft' },
    { value: 'Hunter-Killer Submarine', label: 'Hunter-Killer Submarine' },
    { value: 'Hydrographic survey', label: 'Hydrographic survey' },
    { value: 'Icebreaker / Research', label: 'Icebreaker / Research' },
    { value: 'Icebreaking, aids to navigation', label: 'Icebreaking, aids to navigation' },
    { value: 'Infiltration/Special Ops', label: 'Infiltration/Special Ops' },
    { value: 'Inshore Patrol', label: 'Inshore Patrol' },
    { value: 'Inshore Patrol Craft', label: 'Inshore Patrol Craft' },
    { value: 'Inshore Patrol Vessel', label: 'Inshore Patrol Vessel' },
    { value: 'Intelligence', label: 'Intelligence' },
    { value: 'Intelligence Collector', label: 'Intelligence Collector' },
    { value: 'Intelligence, Research', label: 'Intelligence, Research' },
    { value: 'Interception', label: 'Interception' },
    { value: 'Interception/Law Enforcement', label: 'Interception/Law Enforcement' },
    { value: 'Interceptor', label: 'Interceptor' },
    { value: 'Interdiction, Transport', label: 'Interdiction, Transport' },
    { value: 'Joint Support Ship', label: 'Joint Support Ship' },
    { value: 'Landing Craft', label: 'Landing Craft' },
    { value: 'Landing Craft Mechanized', label: 'Landing Craft Mechanized' },
    { value: 'Landing Craft Personnel', label: 'Landing Craft Personnel' },
    { value: 'Landing Craft Tank', label: 'Landing Craft Tank' },
    { value: 'Landing Craft Utility', label: 'Landing Craft Utility' },
    { value: 'Landing Craft, Utility', label: 'Landing Craft, Utility' },
    { value: 'Landing Platform Dock', label: 'Landing Platform Dock' },
    { value: 'Landing Ship', label: 'Landing Ship' },
    { value: 'Landing Ship Dock', label: 'Landing Ship Dock' },
    { value: 'Landing Ship Logistic', label: 'Landing Ship Logistic' },
    { value: 'Landing Ship Logistics', label: 'Landing Ship Logistics' },
    { value: 'Landing Ship Medium', label: 'Landing Ship Medium' },
    { value: 'Landing Ship Tank', label: 'Landing Ship Tank' },
    { value: 'Landing Ship, Medium', label: 'Landing Ship, Medium' },
    { value: 'Landing Ship, Tank', label: 'Landing Ship, Tank' },
    { value: 'Large Harbour Tug', label: 'Large Harbour Tug' },
    { value: 'Large Patrol Craft', label: 'Large Patrol Craft' },
    { value: 'Large Patrol Craft / Transport', label: 'Large Patrol Craft / Transport' },
    { value: 'Large Patrol Vessel', label: 'Large Patrol Vessel' },
    { value: 'Light Transport', label: 'Light Transport' },
    { value: 'Lighthouse Tender', label: 'Lighthouse Tender' },
    { value: 'Logistic Support', label: 'Logistic Support' },
    { value: 'Logistics', label: 'Logistics' },
    { value: 'Logistics Support', label: 'Logistics Support' },
    { value: 'Logistics, Patrol', label: 'Logistics, Patrol' },
    { value: 'Logistics, Transport', label: 'Logistics, Transport' },
    { value: 'Logistics, amphibious assault', label: 'Logistics, amphibious assault' },
    { value: 'Logistics/Minor Landing', label: 'Logistics/Minor Landing' },
    { value: 'Logistics/Training', label: 'Logistics/Training' },
    { value: 'MHS/C', label: 'MHS/C' },
    { value: 'Maritime interdiction, homeland security, law enforcement', label: 'Maritime interdiction, homeland security, law enforcement' },
    { value: 'Medical', label: 'Medical' },
    { value: 'Midget Submarine', label: 'Midget Submarine' },
    { value: 'Mine Countermeasures Support', label: 'Mine Countermeasures Support' },
    { value: 'Mine Drone', label: 'Mine Drone' },
    { value: 'Mine Warfare', label: 'Mine Warfare' },
    { value: 'Mine Warfare / Patrol', label: 'Mine Warfare / Patrol' },
    { value: 'Mine Warfare Tender', label: 'Mine Warfare Tender' },
    { value: 'Mine countermeasures', label: 'Mine countermeasures' },
    { value: 'Minehunter', label: 'Minehunter' },
    { value: 'Minehunter/Sweeper', label: 'Minehunter/Sweeper' },
    { value: 'Minehunting', label: 'Minehunting' },
    { value: 'Minelayer', label: 'Minelayer' },
    { value: 'Minelayer/MCM Support', label: 'Minelayer/MCM Support' },
    { value: 'Minesweeper', label: 'Minesweeper' },
    { value: 'Minesweeper Coastal', label: 'Minesweeper Coastal' },
    { value: 'Minesweeper Inshore', label: 'Minesweeper Inshore' },
    { value: 'Minesweeper Ocean', label: 'Minesweeper Ocean' },
    { value: 'Minesweeper-Ocean', label: 'Minesweeper-Ocean' },
    { value: 'Minesweeper/Hunter', label: 'Minesweeper/Hunter' },
    { value: 'Minesweeper/Hunter, Coastal', label: 'Minesweeper/Hunter, Coastal' },
    { value: 'Minesweeper/Minehunter', label: 'Minesweeper/Minehunter' },
    { value: 'Minesweeper/Research', label: 'Minesweeper/Research' },
    { value: 'Minesweeping', label: 'Minesweeping' },
    { value: 'Minesweeping, minehunting', label: 'Minesweeping, minehunting' },
    { value: 'Miscellaneous Auxiliary', label: 'Miscellaneous Auxiliary' },
    { value: 'Missile', label: 'Missile' },
    { value: 'Missile Attack', label: 'Missile Attack' },
    { value: 'Missile Boat', label: 'Missile Boat' },
    { value: 'Missile Corvette', label: 'Missile Corvette' },
    { value: 'Missile Craft', label: 'Missile Craft' },
    { value: 'Missile/Gun Attack', label: 'Missile/Gun Attack' },
    { value: 'Multi-role', label: 'Multi-role' },
    { value: 'Multi-role / Stealth', label: 'Multi-role / Stealth' },
    { value: 'Multi-role Frigate', label: 'Multi-role Frigate' },
    { value: 'Multimission cutter in high latitudes', label: 'Multimission cutter in high latitudes' },
    { value: 'Multipurpose Corvette', label: 'Multipurpose Corvette' },
    { value: 'Multipurpose Frigate', label: 'Multipurpose Frigate' },
    { value: 'Multirole', label: 'Multirole' },
    { value: 'Multirole Vessel', label: 'Multirole Vessel' },
    { value: 'Multirole/Air Defence', label: 'Multirole/Air Defence' },
    { value: 'Naval Gunfire Support', label: 'Naval Gunfire Support' },
    { value: 'Navigation Training', label: 'Navigation Training' },
    { value: 'Nuclear Attack Submarine', label: 'Nuclear Attack Submarine' },
    { value: 'Oceanographic Research', label: 'Oceanographic Research' },
    { value: 'Oceanographic Ship', label: 'Oceanographic Ship' },
    { value: 'Offshore Patrol', label: 'Offshore Patrol' },
    { value: 'Offshore Patrol Ship Helicopter', label: 'Offshore Patrol Ship Helicopter' },
    { value: 'Offshore Patrol Vessel', label: 'Offshore Patrol Vessel' },
    { value: 'Offshore Patrol, Support', label: 'Offshore Patrol, Support' },
    { value: 'Offshore patrol', label: 'Offshore patrol' },
    { value: 'Offshore patrol, border protection', label: 'Offshore patrol, border protection' },
    { value: 'Patrol', label: 'Patrol' },
    { value: 'Patrol / Interdiction', label: 'Patrol / Interdiction' },
    { value: 'Patrol / Training', label: 'Patrol / Training' },
    { value: 'Patrol Boat', label: 'Patrol Boat' },
    { value: 'Patrol Craft', label: 'Patrol Craft' },
    { value: 'Patrol Craft / Training', label: 'Patrol Craft / Training' },
    { value: 'Patrol Craft/Missile', label: 'Patrol Craft/Missile' },
    { value: 'Patrol Ship', label: 'Patrol Ship' },
    { value: 'Patrol Submarine', label: 'Patrol Submarine' },
    { value: 'Patrol, ASW', label: 'Patrol, ASW' },
    { value: 'Patrol, Anti-Surface', label: 'Patrol, Anti-Surface' },
    { value: 'Patrol, Fishery Protection', label: 'Patrol, Fishery Protection' },
    { value: 'Patrol, Ice Operations', label: 'Patrol, Ice Operations' },
    { value: 'Patrol, Pollution Control', label: 'Patrol, Pollution Control' },
    { value: 'Patrol, Torpedo Recovery', label: 'Patrol, Torpedo Recovery' },
    { value: 'Patrol, Training', label: 'Patrol, Training' },
    { value: 'Patrol, UN Operations', label: 'Patrol, UN Operations' },
    { value: 'Patrol, Utility', label: 'Patrol, Utility' },
    { value: 'Patrol/ASW', label: 'Patrol/ASW' },
    { value: 'Patrol/Combat', label: 'Patrol/Combat' },
    { value: 'Patrol/Fishery Protection', label: 'Patrol/Fishery Protection' },
    { value: 'Patrol/Interception', label: 'Patrol/Interception' },
    { value: 'Patrol/Missile', label: 'Patrol/Missile' },
    { value: 'Patrol/Multirole', label: 'Patrol/Multirole' },
    { value: 'Patrol/Rescue', label: 'Patrol/Rescue' },
    { value: 'Patrol/SAR', label: 'Patrol/SAR' },
    { value: 'Patrol/Strike', label: 'Patrol/Strike' },
    { value: 'Patrol/Torpedo', label: 'Patrol/Torpedo' },
    { value: 'Polar research, icebreaking', label: 'Polar research, icebreaking' },
    { value: 'Police Patrol', label: 'Police Patrol' },
    { value: 'Pollution Control', label: 'Pollution Control' },
    { value: 'Port Security, Law Enforcement', label: 'Port Security, Law Enforcement' },
    { value: 'Port Security, Search and Rescue', label: 'Port Security, Search and Rescue' },
    { value: 'Power Projection', label: 'Power Projection' },
    { value: 'Primary Casualty Receiving Ship', label: 'Primary Casualty Receiving Ship' },
    { value: 'Raiding', label: 'Raiding' },
    { value: 'Raiding Craft', label: 'Raiding Craft' },
    { value: 'Rapid Intervention Vessel', label: 'Rapid Intervention Vessel' },
    { value: 'Replenishment', label: 'Replenishment' },
    { value: 'Replenishment Oiler', label: 'Replenishment Oiler' },
    { value: 'Replenishment Oiler Helicopter', label: 'Replenishment Oiler Helicopter' },
    { value: 'Replenishment Tanker', label: 'Replenishment Tanker' },
    { value: 'Replenishment, Support', label: 'Replenishment, Support' },
    { value: 'Research', label: 'Research' },
    { value: 'Research & Testing', label: 'Research & Testing' },
    { value: 'Rescue Submersible', label: 'Rescue Submersible' },
    { value: 'Response Boat', label: 'Response Boat' },
    { value: 'River Gunboat', label: 'River Gunboat' },
    { value: 'River Minesweeper', label: 'River Minesweeper' },
    { value: 'River Patrol', label: 'River Patrol' },
    { value: 'River Patrol Craft', label: 'River Patrol Craft' },
    { value: 'River/Lake Patrol', label: 'River/Lake Patrol' },
    { value: 'Riverine special operations', label: 'Riverine special operations' },
    { value: 'Royal Yacht Support', label: 'Royal Yacht Support' },
    { value: 'STOBAR Carrier', label: 'STOBAR Carrier' },
    { value: 'STOVL Carrier', label: 'STOVL Carrier' },
    { value: 'Sail Training', label: 'Sail Training' },
    { value: 'Sail Training Ship', label: 'Sail Training Ship' },
    { value: 'Salvage Ship', label: 'Salvage Ship' },
    { value: 'Salvage, Rescue, Patrol', label: 'Salvage, Rescue, Patrol' },
    { value: 'Salvage, Search and Rescue', label: 'Salvage, Search and Rescue' },
    { value: 'Salvage, Towing', label: 'Salvage, Towing' },
    { value: 'Salvage/Diving', label: 'Salvage/Diving' },
    { value: 'Search and Rescue', label: 'Search and Rescue' },
    { value: 'Search and rescue, law enforcement', label: 'Search and rescue, law enforcement' },
    { value: 'Search and rescue, law enforcement, homeland security', label: 'Search and rescue, law enforcement, homeland security' },
    { value: 'Sealift, Transport', label: 'Sealift, Transport' },
    { value: 'Service Ship', label: 'Service Ship' },
    { value: 'Special Forces', label: 'Special Forces' },
    { value: 'Specialized missions, transport', label: 'Specialized missions, transport' },
    { value: 'Strategic Deterrent', label: 'Strategic Deterrent' },
    { value: 'Strategic Missile Submarine', label: 'Strategic Missile Submarine' },
    { value: 'Strike', label: 'Strike' },
    { value: 'Submarine', label: 'Submarine' },
    { value: 'Submarine Rescue', label: 'Submarine Rescue' },
    { value: 'Submarine Support', label: 'Submarine Support' },
    { value: 'Submarine technology training', label: 'Submarine technology training' },
    { value: 'Supply', label: 'Supply' },
    { value: 'Supply, SAR, Tug', label: 'Supply, SAR, Tug' },
    { value: 'Support', label: 'Support' },
    { value: 'Support Ship', label: 'Support Ship' },
    { value: 'Support Ship / Submarine Tender', label: 'Support Ship / Submarine Tender' },
    { value: 'Support Ship/Command', label: 'Support Ship/Command' },
    { value: 'Support Tanker', label: 'Support Tanker' },
    { value: 'Support Vessel', label: 'Support Vessel' },
    { value: 'Surveillance', label: 'Surveillance' },
    { value: 'Surveillance / Patrol', label: 'Surveillance / Patrol' },
    { value: 'Survey', label: 'Survey' },
    { value: 'Survey & Buoy Tender', label: 'Survey & Buoy Tender' },
    { value: 'Survey & Research', label: 'Survey & Research' },
    { value: 'Survey / Antarctic Support', label: 'Survey / Antarctic Support' },
    { value: 'Survey Craft', label: 'Survey Craft' },
    { value: 'Survey Ship', label: 'Survey Ship' },
    { value: 'Survey and Research', label: 'Survey and Research' },
    { value: 'Survey and Supply', label: 'Survey and Supply' },
    { value: 'Survey, Oceanographic', label: 'Survey, Oceanographic' },
    { value: 'Survey, Search and Rescue', label: 'Survey, Search and Rescue' },
    { value: 'Survey/Buoy Tender', label: 'Survey/Buoy Tender' },
    { value: 'Survey/Patrol', label: 'Survey/Patrol' },
    { value: 'Survey/Research', label: 'Survey/Research' },
    { value: 'Survey/Training', label: 'Survey/Training' },
    { value: 'Tank / Vehicle Transport', label: 'Tank / Vehicle Transport' },
    { value: 'Tank Landing Ship', label: 'Tank Landing Ship' },
    { value: 'Tanker', label: 'Tanker' },
    { value: 'Torpedo Attack', label: 'Torpedo Attack' },
    { value: 'Torpedo Recovery', label: 'Torpedo Recovery' },
    { value: 'Towing', label: 'Towing' },
    { value: 'Towing, Multi-role', label: 'Towing, Multi-role' },
    { value: 'Towing, Support', label: 'Towing, Support' },
    { value: 'Training', label: 'Training' },
    { value: 'Training / ASW', label: 'Training / ASW' },
    { value: 'Training Craft', label: 'Training Craft' },
    { value: 'Training Frigate', label: 'Training Frigate' },
    { value: 'Training Ship', label: 'Training Ship' },
    { value: 'Training Vessel', label: 'Training Vessel' },
    { value: 'Training, patrol', label: 'Training, patrol' },
    { value: 'Training/Command', label: 'Training/Command' },
    { value: 'Trials Support', label: 'Trials Support' },
    { value: 'Transport', label: 'Transport' },
    { value: 'Transport / Minelayer', label: 'Transport / Minelayer' },
    { value: 'Transport Ship', label: 'Transport Ship' },
    { value: 'Transport of equipment and troops', label: 'Transport of equipment and troops' },
    { value: 'Transport, Logistics', label: 'Transport, Logistics' },
    { value: 'Troop / Cargo Carrier', label: 'Troop / Cargo Carrier' },
    { value: 'Troop Transport', label: 'Troop Transport' },
    { value: 'Troop Transport, Patrol', label: 'Troop Transport, Patrol' },
    { value: 'Tug', label: 'Tug' },
    { value: 'Tug / Patrol', label: 'Tug / Patrol' },
    { value: 'Tug / Tender', label: 'Tug / Tender' },
    { value: 'Tug / Utility', label: 'Tug / Utility' },
    { value: 'Tug/SAR', label: 'Tug/SAR' },
    { value: 'Tug/Salvage', label: 'Tug/Salvage' },
    { value: 'Tug/Torpedo Tender', label: 'Tug/Torpedo Tender' },
    { value: 'Underway Replenishment', label: 'Underway Replenishment' },
    { value: 'Unmanned Patrol Craft', label: 'Unmanned Patrol Craft' },
    { value: 'Utility', label: 'Utility' },
    { value: 'Utility / Transport', label: 'Utility / Transport' },
    { value: 'Vehicle / Cargo Transport', label: 'Vehicle / Cargo Transport' },
    { value: 'Water Supply', label: 'Water Supply' },
    { value: 'Water Tanker', label: 'Water Tanker' },
    { value: 'Yacht', label: 'Yacht' },
    { value: 'Yacht/Tender', label: 'Yacht/Tender' }
];

export const HULL_FORMS = [
    { value: 'Monohull', label: 'Monohull' },
    { value: 'Catamaran', label: 'Catamaran' },
    { value: 'Trimaran', label: 'Trimaran' },
    { value: 'SWATH', label: 'SWATH (Small Waterplane Area Twin Hull)' },
    { value: 'Hydrofoil', label: 'Hydrofoil' },
    { value: 'Hovercraft', label: 'Hovercraft' }
];

export const HULL_SHAPES = [
    { value: 'Sleek', label: 'Sleek' },
    { value: 'Fine', label: 'Fine' },
    { value: 'Bulky', label: 'Bulky' },
    { value: 'Beamish', label: 'Beamish' },
    { value: 'Flat-decked', label: 'Flat-decked' }
];

export const BOW_SHAPES = [
    { value: 'Raked', label: 'Raked' },
    { value: 'Fine', label: 'Fine' },
    { value: 'Bluff', label: 'Bluff' },
    { value: 'Bulbous', label: 'Bulbous' },
    { value: 'Axe bow', label: 'Axe bow' },
    { value: 'Clipper', label: 'Clipper' },
    { value: 'Icebreaker', label: 'Icebreaker' },
    { value: 'Wave-piercing', label: 'Wave-piercing' },
    { value: 'Bluff/Bulbous', label: 'Bluff/Bulbous' },
];

export const SUPERSTRUCTURE_LAYOUTS = [
    { value: 'Single continuous', label: 'Single continuous' },
    { value: 'Central block', label: 'Central block' },
    { value: 'Split fore/aft', label: 'Split fore/aft' },
    { value: 'Minimal', label: 'Minimal' },
    { value: 'Stealthy/angular', label: 'Stealthy/angular' },
    { value: 'Cluttered/asymmetric', label: 'Cluttered/asymmetric' },
    { value: 'Towering island', label: 'Towering island' },
    { value: 'Island starboard', label: 'Island starboard' },
    { value: 'Bulky/Merchant-derived', label: 'Bulky/Merchant-derived' }
];

export const FUNNEL_ARRANGEMENTS = [
    { value: 'Single compact', label: 'Single compact' },
    { value: 'Twin side-by-side', label: 'Twin side-by-side' },
    { value: 'Twin fore-aft', label: 'Twin fore-aft' },
    { value: 'Paired', label: 'Paired' },
    { value: 'Integrated', label: 'Integrated' },
    { value: 'Underwater exhaust', label: 'Underwater exhaust' },
    { value: 'Island-mounted', label: 'Island-mounted' },
    { value: 'Three funnels', label: 'Three funnels' },
    { value: 'Four funnels', label: 'Four funnels' }
];

export const FUNNEL_SHAPES = [
    { value: 'Tall/stack', label: 'Tall/stack' },
    { value: 'Squat/boxy', label: 'Squat/boxy' },
    { value: 'Raked', label: 'Raked' },
    { value: 'Vertical', label: 'Vertical' },
    { value: 'Angled', label: 'Angled' },
    { value: 'Integrated', label: 'Integrated' },
    { value: 'Stealthy/angular', label: 'Stealthy/angular' },
    { value: 'Raked/Stealth', label: 'Raked/Stealth' },
    { value: 'Enclosed mast-funnel', label: 'Enclosed mast-funnel' }
];

export const FUNNEL_SPACINGS = [
    { value: 'Close', label: 'Close' },
    { value: 'Wide', label: 'Wide' },
    { value: 'Fore-aft separated', label: 'Fore-aft separated' },
    { value: 'Integrated', label: 'Integrated' }
];

export const SIZE_CATEGORIES = [
    { value: 'Very Small (<500 tons)', label: 'Very Small (<500 tons)' },
    { value: 'Small (500-2,000 tons)', label: 'Small (500-2,000 tons)' },
    { value: 'Medium (2,000-6,000 tons)', label: 'Medium (2,000-6,000 tons)' },
    { value: 'Large (6,000-12,000 tons)', label: 'Large (6,000-12,000 tons)' },
    { value: 'Very Large (12,000-30,000 tons)', label: 'Very Large (12,000-30,000 tons)' },
    { value: 'Extra Large (>30,000 tons)', label: 'Extra Large (>30,000 tons)' }
];

export const MAST_CONFIGURATIONS = [
    { value: 'Pole masts', label: 'Pole masts' },
    { value: 'Lattice mast', label: 'Lattice mast' },
    { value: 'Tripod mast', label: 'Tripod mast' },
    { value: 'Tower mast', label: 'Tower mast' },
    { value: 'Integrated mast', label: 'Integrated mast' },
    { value: 'Enclosed mast', label: 'Enclosed mast' },
    { value: 'Stealth mast', label: 'Stealth mast' },
    { value: 'Single foremast', label: 'Single foremast' },
    { value: 'Two masts', label: 'Two masts' },
    { value: 'Three masts', label: 'Three masts' },
    { value: 'Minimal', label: 'Minimal' },
    { value: 'Minimal mast', label: 'Minimal mast' }
];

export const FREEBOARD_HEIGHTS = [
    { value: 'Very Low', label: 'Very Low' },
    { value: 'Low', label: 'Low' },
    { value: 'Medium', label: 'Medium' },
    { value: 'High', label: 'High' },
    { value: 'Very High', label: 'Very High' }
];

export const RADAR_CONFIGURATIONS = [
    { value: 'None/Minimal', label: 'None/Minimal' },
    { value: 'Simple arrays (1-2 basic radars)', label: 'Simple arrays (1-2 basic radars)' },
    { value: 'Moderate arrays (multiple specialized radars)', label: 'Moderate arrays (multiple specialized radars)' },
    { value: 'Complex arrays (AEGIS-type systems)', label: 'Complex arrays (AEGIS-type systems)' }
];

export const GUNMOUNT_POSITIONS = [
    { value: 'Forward only', label: 'Forward only' },
    { value: 'Aft only', label: 'Aft only' },
    { value: 'Forward and Aft', label: 'Forward and Aft' },
    { value: 'Forward and Amidships', label: 'Forward and Amidships' },
    { value: 'Amidships', label: 'Amidships' },
    { value: 'Multiple positions', label: 'Multiple positions' },
    { value: 'Broadside', label: 'Broadside' }
];

export const GUNMOUNT_SIZES = [
    { value: 'Small (<30mm - CIWS)', label: 'Small (<30mm - CIWS)' },
    { value: 'Medium (30mm-76mm)', label: 'Medium (30mm-76mm)' },
    { value: 'Large (76mm-127mm)', label: 'Large (76mm-127mm)' },
    { value: 'Very Large (>127mm)', label: 'Very Large (>127mm)' },
    { value: 'Multiple calibers', label: 'Multiple calibers' }
];

export const LENGTH_TO_BEAM_RATIOS = [
    { value: 'Very Short and wide', label: 'Very Short and wide' },
    { value: 'Short and wide', label: 'Short and wide' },
    { value: 'Balanced', label: 'Balanced' },
    { value: 'Long and narrow', label: 'Long and narrow' },
    { value: 'Very Long and narrow', label: 'Very Long and narrow' }
];

export const INITIAL_FORM_STATE = {
    // Basic Identification
    ship_name: '',
    hull_number: '',
    country: '',
    base_port: '',
    ship_class: '',
    ship_type: '',
    ship_role: '',

    // Physical Dimensions
    displacement_full_load_tons: '',
    length_metres_min: '',
    length_metres_max: '',
    beam_metres_min: '',
    beam_metres_max: '',
    draught_metres_min: '',
    draught_metres_max: '',
    speed_knots_min: '',
    speed_knots_max: '',
    complement_total_personnel: '',

    // Hull Characteristics
    hull_form: '',
    hull_shape: '',
    bow_shape: '',
    length_to_beam_ratio: '',
    approximate_size_category: '',
    freeboard_height: '',

    // Superstructure
    superstructure_layout: '',
    distinct_superstructure_blocks_number: '',

    // Funnels/Smokestacks
    funnel_arrangement: '',
    funnels_total: '',
    funnel_shape: '',
    spacing_between_funnels: '',
    smokestacks_total: '',

    // Masts and Radars
    mast_configuration: '',
    radar_configuration: '',
    radar_airsearch: '',
    radar_surfacesearch: '',
    radar_firecontrol: '',

    // Weapons and Systems
    main_machinery: '',
    main_gun: '',
    main_gun_caliber_inches: '',
    main_gun_turrets_total: '',
    torpedo_tubes_visible_number: '',
    gunmounts_position: '',
    gunmounts_number: '',
    gunmounts_size: '',
    missile_launchers: '',
    CIWS: '',
    CIWS_positions: '',
    sonar: '',

    // Aviation Facilities
    flight_deck: '',
    hangar: '',
    hangar_capacity: '',
    helicopter_platform: '',
    helicopter_capacity: '',

    // Build Information
    builder: '',
    launch_year: '',
    commission_year: '',

    // Number of matches to return
    top_k: '5',
};

export const AUTOCOMPLETE_DATA = {
    countries: [
        'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
        'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
        'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
        'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria',
        'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
        'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
        'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
        'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica',
        'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador',
        'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji',
        'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
        'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
        'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
        'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
        'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
        'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
        'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
        'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova',
        'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
        'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
        'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau',
        'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
        'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis',
        'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
        'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles',
        'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
        'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
        'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
        'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
        'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
        'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu',
        'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
    ],
    ports: [
        'Norfolk', 'San Diego', 'Pearl Harbor', 'Portsmouth', 'Yokosuka',
        'Sasebo', 'Toulon', 'Brest', 'Kiel', 'Wilhelmshaven', 'La Spezia',
        'Taranto', 'Halifax', 'Esquimalt', 'Sydney', 'Devonport', 'Faslane',
        'Severomorsk', 'Vladivostok', 'Qingdao', 'Shanghai', 'Mumbai', 'Karachi'
    ]
};